version: "3"
services:
  
  frontend:
   image:chaitanyadevelops/videocall_client:latest
   ports:
    -  3000:3000
   container_name: mern-frontend
   networks:
    -  mern-stack-net
   depends_on:
    - backend
   stdin_open: true
   tty: true

  backend:
   image:chaitanyadevelops/videocall_server:latest
   ports:
     - 2442:2442
   container_name: mern-backend
   networks:
     - mern-stack-net
   depends_on:
    - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local